def scale_test():
    import random
    scales = {"C Major": ["C", "D", "E", "F", "G", "A", "B"],
              "D Major": ["D", "E", "F#", "G", "A", "B", "C#",],
              "E Major": ["E", "F#", "G#", "A", "B", "C#", "D#"],
              "F Major": ["F", "G", "A", "Bb", "C", "D", "E"],
              "G Major": ["G", "A", "B", "C", "D", "E", "F#"],
              "A Major": ["A", "B", "C#", "D", "E", "F#", "G#"],
              "B Major": ["B", "C#", "D#", "E", "F#", "G#", "A#"],
              "Db Major": ["Db", "Eb", "F", "Gb", "Ab", "Bb", "C"],
              "Eb Major": ["Eb", "F", "G", "Ab", "Bb", "C", "D"],
              "F# Major": ["F#", "G#", "A#", "B", "C#", "D#", "E#"],
              "Gb Major": ["Gb", "Ab", "Bb", "Cb", "Db", "Eb", "F"],
              "Ab Major": ["Ab", "Bb", "C", "Db", "Eb", "F", "G"],
              "Bb Major": ["Bb", "C", "D", "Eb", "F", "G", "A"], 
              "Cb Major": ["Cb", "Db", "Eb", "Fb", "Gb", "Ab", "Bb"],
              "C# Major": ["C#", "D#", "E#", "F#", "G#", "A#", "B#"],
              "A natural minor": ["A", "B", "C", "D", "E", "F", "G"],
              "B natural minor": ["B", "C#", "D", "E", "F#", "G", "A"],
              "C natural minor": ["C", "D", "Eb", "F", "G", "Ab", "Bb"],
              "D natural minor": ["D", "E", "F", "G", "A", "Bb", "C"],
              "E natural minor": ["E", "F#", "G", "A", "B", "C", "D"],
              "F natural minor": ["F", "G", "Ab", "Bb", "C", "Db", "Eb"],
              "G natural minor": ["G", "A", "Bb", "C", "D", "Eb", "F"],
              "A natural minor": ["A", "B", "C", "D", "E", "F", "G"],
              "B natural minor": ["B", "C#", "D", "E", "F#", "G", "A"], 
              "Bb natural minor": ["Bb", "C", "Db", "Eb", "F", "Gb", "Ab"],
              "C# natural minor": ["C#", "D#", "E", "F#", "G#", "A", "B"],
              "D# natural minor": ["D#", "E#", "F#", "G#", "A#", "B", "C#"],
              "Eb natural minor": ["Eb", "F", "Gb", "Ab", "Bb", "Cb", "Db"],
              "F# natural minor": ["F#", "G#", "A", "B", "C#", "D", "E",], 
              "G# natural minor": ["G#", "A#", "B", "C#", "D#", "E", "F#"],
              "Ab natural minor": ["Ab", "Bb", "Cb", "Db", "Eb", "Fb", "Gb",],
              "A# natural minor": ["A#", "B#", "C#", "D#", "E#", "F#", "G#"],
              }
    