print('Hello!')
name=input('What is your name?')
print('Hello')
print(name)
print('In order to proceed, you must answer the following questions.')
color=input('What is your favorite color?')
print('Excellent! I love the color')
print(color)
food=input('What is your favorite food?')
print('Fantastic! I happen to think that')
print(food)
print('Is quite scrumptious as well')
print('Final question:')
number=input('How much wood could a woodchuck chuck if a woodchuck could chuck wood?')
print(number)
print('That is a lot of wood')
